// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAh4uUjyHLf43bWicQ5bIJ4TbFpP0-JLC8',
    appId: '1:477479355989:android:8167801543807b4eb9b6dc',
    messagingSenderId: '477479355989',
    projectId: 'sample-firebase-ai-app-f9103',
    storageBucket: 'sample-firebase-ai-app-f9103.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDa11SI_5dWrOb86WbWsKEgbW8HNgewfgk',
    appId: '1:477479355989:ios:a4a70eca4e9416a4b9b6dc',
    messagingSenderId: '477479355989',
    projectId: 'sample-firebase-ai-app-f9103',
    storageBucket: 'sample-firebase-ai-app-f9103.firebasestorage.app',
    iosBundleId: 'com.example.flatter',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFx49Dk_-_BKEpC3X6gNl41M76MSulZ1U',
    appId: '1:477479355989:web:c6ae42e23fbe9691b9b6dc',
    messagingSenderId: '477479355989',
    projectId: 'sample-firebase-ai-app-f9103',
    authDomain: 'sample-firebase-ai-app-f9103.firebaseapp.com',
    storageBucket: 'sample-firebase-ai-app-f9103.firebasestorage.app',
  );
}
